//получение списка друзей
GET http://localhost:8080/get HTTP/1.1
content-type: application/json

{"country":"RU","provider":"Rond","bandwidth":"проверка3","response_time":"145","country":"RU","provider":"Rond","bandwidth":"проверка4","response_time":"145"}


###

//	Country      string `json:"country"`
//	Provider     string `json:"provider"`
//	Bandwidth    string `json:"bandwidth"`
//	ResponseTime string `json:"response_time"`

POST http://localhost:8383/getall HTTP/1.1
//content-type: application/json
###